/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmc;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dejvk
 */
public class jfMain extends javax.swing.JFrame {

    /**
     * Creates new form jfMain
     */
    public jfMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jlOnlineList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jbMenuServerCheck = new javax.swing.JButton();
        jbMenuUpdateCharList = new javax.swing.JButton();
        jlOnlineCharsUpdateTimeLabel = new javax.swing.JLabel();
        jlOnlineCharsUpdateTime = new javax.swing.JLabel();
        jbShowCharDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMC");

        jlOnlineList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "- no characters -" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlOnlineList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlOnlineList);

        jLabel1.setText("Online players:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        jbMenuServerCheck.setText("Server check");
        jbMenuServerCheck.setFocusable(false);
        jbMenuServerCheck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMenuServerCheck.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMenuServerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuServerCheckActionPerformed(evt);
            }
        });
        jToolBar1.add(jbMenuServerCheck);

        jbMenuUpdateCharList.setText("Update characters");
        jbMenuUpdateCharList.setFocusable(false);
        jbMenuUpdateCharList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMenuUpdateCharList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMenuUpdateCharList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuUpdateCharListActionPerformed(evt);
            }
        });
        jToolBar1.add(jbMenuUpdateCharList);

        jlOnlineCharsUpdateTimeLabel.setText("Last update:");

        jlOnlineCharsUpdateTime.setText("- none -");

        jbShowCharDetails.setText(">>");
        jbShowCharDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowCharDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlOnlineCharsUpdateTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlOnlineCharsUpdateTime)
                                .addGap(32, 32, 32)
                                .addComponent(jbShowCharDetails))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 476, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlOnlineCharsUpdateTimeLabel)
                    .addComponent(jlOnlineCharsUpdateTime)
                    .addComponent(jbShowCharDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMenuServerCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuServerCheckActionPerformed
        Server s = new Server("www.pk-nostalgia.cz");
        if (s.state())
            JOptionPane.showMessageDialog(this, "Server " + s.getHostname() + " is available.", "Server state check", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Server " + s.getHostname() + " is NOT available.", "Server state check", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jbMenuServerCheckActionPerformed

    private void jbMenuUpdateCharListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuUpdateCharListActionPerformed
        List<Character> db = new CharacterDaoTest().getOnlineCharacters();
        DefaultListModel chars = new DefaultListModel();
        for (Character c : db){
            chars.addElement(c.getName());
        }
        jlOnlineList.setModel(chars);
        jlOnlineCharsUpdateTime.setText(new SimpleDateFormat("HH:mm").format(Calendar.getInstance().getTime()));
    }//GEN-LAST:event_jbMenuUpdateCharListActionPerformed

    private void jbShowCharDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowCharDetailsActionPerformed
        int index = jlOnlineList.getSelectedIndex();
        if (index >= 0)
            JOptionPane.showMessageDialog(this, "Klikl jsi na " + jlOnlineList.getSelectedValue());
        else
            JOptionPane.showMessageDialog(this, "Nejprve vyber postavu!", null, JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbShowCharDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbMenuServerCheck;
    private javax.swing.JButton jbMenuUpdateCharList;
    private javax.swing.JButton jbShowCharDetails;
    private javax.swing.JLabel jlOnlineCharsUpdateTime;
    private javax.swing.JLabel jlOnlineCharsUpdateTimeLabel;
    private javax.swing.JList jlOnlineList;
    // End of variables declaration//GEN-END:variables
}
